name: Auto Merge PR

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
        - 'main'
  workflow_dispatch:

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Enable Auto-Merge
        env:
          GH_TOKEN: ${{ secrets.MANIFEST_REPO_PAT }} 
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge "$PR_URL" --auto --squash
